// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/14fe4313f4a1cf69add3505a2ab1dbc690dc2116/ng-cordova/network.d.ts
declare namespace ngCordova {

  export interface INetworkInformationService {

      getNetwork(): string;
      isOnline(): boolean;
      isOffline(): boolean;
      clearOfflineWatch(): void;
      clearOnlineWatch(): void;
  }

}